### ISSUE TITLE
link on read.me

### ISSUE THREAD

**Issue by lucarv** [Azure/azure-iot-connected-factory#2]
the link in the read.me page that should direct to an explanation of the solution and the "script" takes to a page that only shows the other two pre configured.

**Comment by barnstee** [comment]
I know. :-) We're working on this right now. ETA Monday.

**Comment by SeanStayn** [comment]
I have found a spelling mistake: 

# Connected factory preconfigured solution

The connected factory preconfigured solution illustrates how you can get started with your Industrie 4.0 digital **trnasformation.** It brings together key Azure IoT services to enable the following features: OPC UA data ingestion, OPC UA server management, rules and actions and Azure Time Series Insights.

**Comment by hansgschossmann** [comment]
Both issues are resolved. Typo fixed and the link https://docs.microsoft.com/en-us/azure/iot-suite/iot-suite-getstarted-preconfigured-solutions has now also a walk-through of the Connected factory preconfigured solution.
