### ISSUE TITLE
Pressure always show 0 mbar in dashboard

### ISSUE THREAD

**Issue by robert4os** [Azure/azure-iot-connected-factory#25]
However, when clicking the pressure row then the time series visuals at the right shows non-zero values.

Also the OPC UA Server correctly shows non-zero values for pressure .

**Comment by hansgschossmann** [comment]
We are aware of this issue and are going to address this in the near future. This also prevents showing values of OPC UA servers a user adds to Cf.

**Comment by J7S** [comment]
Hans,
does your last comment mean that we are currently not able to show any values of a newly added OPC UA server in connected factory?
Is there any workaround?
Thaks!
Joerg

**Comment by hansgschossmann** [comment]
This is fixed with the 1711 release.
