### ISSUE TITLE
Question: Microsoft.Rdx.Client not longer supported?

### ISSUE THREAD

**Issue by devdeer-alex** [Azure/azure-iot-connected-factory#28]
The sample utilizes the Microsoft.Rdx.Client NuGet a lot. When I search for this package on NuGet it is unlisted now. [This page](https://libraries.io/nuget/Microsoft.Rdx.Client) states that the package was removed. What would be the replacement to this package?

**Comment by gasherma** [comment]
We are using a beta version of the NuGet package, TSI team is working on an RTM version which we will then integrate.

**Comment by jillcary** [comment]
I believe the replacement currently is the Time Series Insights REST api:
https://docs.microsoft.com/en-us/azure/time-series-insights/time-series-insights-query-data-csharp

**Comment by hansgschossmann** [comment]
The REST API has always been there. We are in discussion with the TSI team. I will update this issue as soon as i have a qualified answer.

**Comment by hansgschossmann** [comment]
This will not happen any more in this CY. It is the NuGet package is on their backlog for next year.

**Comment by barnstee** [comment]
Correct, the official interface is REST.
