### ISSUE TITLE
Alert not Showing!?

### ISSUE THREAD

**Issue by ryan-ms** [Azure/azure-iot-connected-factory#31]
Hi,

I deployed the connected factory. And add a new factory in ContosoTopologyDescription.json.
Besides, I added some OpcNodes and set the alarm rule just like the code below.
`{
  "NodeId": "ns=2;s=MTCP_CurrentValueTask.CO2",
  "SymbolicName": "CO2",
  "OpCode": "Avg",
  "Units": "ppm",
  "Maximum": 200
}`

After that, I deployed the website from my visual studio again.
And now, I can received the data from my opcua server successfully. (not from simulator)

But the alarm never shows. I am sure the ppm of CO2 is always higher than 200.

Did I miss something?
Please give me some hints if you have some ideas, thank you.

**Comment by hansgschossmann** [comment]
Right now we do not support alerts for the actual data values. We only support alerts for KPIs and OEEs.
This would be a nice feature to add.

**Comment by hansgschossmann** [comment]
Nothing heard back. Closing.
