### ISSUE TITLE
RdxAuthenticationClientSecret is blank

### ISSUE THREAD

**Issue by rajat-barik** [Azure/azure-iot-connected-factory#35]
RdxAuthenticationClientSecret value is blank. Please guide what this value refers to so that I can manually fill it in the Application settings of webapp.

**Comment by hansgschossmann** [comment]
This value is used for the WebApp to authenticate against TimeSeriesInsights. You need to go to your resource group in the Azure Portal, lookup your the App Registration of your CF deployment under "Azure Active Directory -> App registrations", create a new Key and put it as value into the environment of your App Service in the resource group of the WebApp. 
Strange is that it is empty. How have you deployed the CF? Via build script or via www.azureiotsolutions.com? Have you got any errors or warnings?

**Comment by barnstee** [comment]
Closed as this has been answered.
