### ISSUE TITLE
Error while running the build.ps1 script

### ISSUE THREAD

**Issue by Shruthi-Patil** [Azure/azure-iot-connected-factory#36]
I followed the procedure mentioned on the page : https://github.com/Azure/azure-iot-connected-factory
I'm getting the following error :
![image](https://user-images.githubusercontent.com/43697941/46581123-c8bff900-ca32-11e8-8237-aebbe2859594.png) 
Additional Info:
- Script is successfully built
- Versions of programs are up to date.

**Comment by hansgschossmann** [comment]
Please ensure you have the Azure PowerShell Command Line Interface installed (from here: https://azure.microsoft.com/en-us/downloads/). The current CF is tested with the April 2018 version (check in "Add or remove program" of you dev box).

In PowerShell "Find-Module AzureRm.Resources" should report Version 6.6.0 and "Get-Command -Module AzureRm.Resources -Name Get-AzureRmADServicePrincipal" should report Verions 5.5.2

**Comment by Rikoz02** [comment]
Same issue, I'd like to know which modules (and versions) do you have installed on your local machine

**Comment by barnstee** [comment]
Closed as this has been answered.
