### ISSUE TITLE
Error on build - wrong package path

### ISSUE THREAD

**Issue by danielrmendes** [Azure/azure-iot-connected-factory#41]
Hello,
Followed the instructions and all seems fine. However when I try to build I get the following error, replicated to all packages:

`Could not find a part of the path 'C:\Users\thisUser\Documents\azure-iot-connected-factory\ \packages\System.Collections.Specialized.4.3.0'.`

The packages exist and are located at:
`'C:\Users\thisUser\Documents\azure-iot-connected-factory\packages\System.Collections.Specialized.4.3.0'.`
That is, without the extra "\ \".
Been wrapping my head around what is causing this but cannot find a solution.

**Comment by palyi** [comment]
I could reproduce the same error with the latest release. All package paths get a "space+\", corrupting each package reference at build.  See screenshot.

**Comment by AzoricoTC** [comment]
We managed a temporary fix for this by removing the "\" in "$(MSBuildProjectDirectory)\packages" at lines 39, 40 e 44.

**Comment by studentpra** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not find a part of the path 'D:\azure-iot-connected-factory\ \packages\jQuery.UI.i18n.1.10.2'.	WebApp		

hi i am having error above realted to path as its having double \\ before package applied above solution as mentioned in comment also.

Please, help me with issue so that i can build and do some changes in to it.

**Comment by AzoricoTC** [comment]
@studentpra 

Hey there go to the .nuget folder, open the Nuget.targets file and remove the extra "\"  on the aforementioned lines. Should fix all those path errors.

**Comment by studentpra** [comment]
Hi @AzoricoTC ,

Is there any way to show time series insights data to power bi dashboard 

i tried to search a lot but not able to connect power bi to time series insights 
Please, let me know the solution if any 

thanks
Prateek

**Comment by sandervandevelde** [comment]
@AzoricoTC your fix works, thanks. Remove in total 4 times a slash in NuGet.targets.

**Comment by barnstee** [comment]
Closed as this has been asnwered.
