### ISSUE TITLE
NOT ABLE TO BUILD 

### ISSUE THREAD

**Issue by studentpra** [Azure/azure-iot-connected-factory#42]
Severity	Code	Description	Project	File	Line	Suppression State
Error	Could not find a part of the path 'D:\azure-iot-connected-factory\ \packages\jQuery.UI.i18n.1.10.2'. WebApp

hi i am having error above realted to path as its having double \ before package applied above solution as mentioned in comment also.

Please, help me with issue so that i can build and do some changes in to it.
@AzoricoTC

**Comment by barnstee** [comment]
Closed as duplicate. The package path is incorrect.
