### ISSUE TITLE
time series insights to power bi

### ISSUE THREAD

**Issue by studentpra** [Azure/azure-iot-connected-factory#44]
Hi @AzoricoTC ,

Is there any way to show time series insights data to power bi dashboard

i tried to search a lot but not able to connect power bi to time series insights
Please, let me know the solution if any

thanks
Prateek

**Comment by MatthijsvdVeer** [comment]
I think right now it's not possible. However the new TSI will store your cold path in blob storage. I think power bi desktop supports blob storage input. So maybe that is the way to go.

**Comment by barnstee** [comment]
Closed as this has been answered.
