### ISSUE TITLE
Exception while building using build.ps1 ( Exception calling "Import" with "3" argument(s): "The system cannot find the file specified.)

### ISSUE THREAD

**Issue by deepakagra** [Azure/azure-iot-connected-factory#46]
Facing exception while building the project.
[BuildingConnectedFactory.log](https://github.com/Azure/azure-iot-connected-factory/files/3088301/BuildingConnectedFactory.log)

**Comment by deepakagra** [comment]
Please note that I could build the project successfully using Visual Studio. Exceptions happening while deploying using build ps1

**Comment by marcschier** [comment]
The issue starts earlier, the script requires .net sdk 1.1 and that was not found.  Can you try installing .net sdk 1.1 and try running the script again?
