### ISSUE TITLE
Wrong timestamp property name after deploying

### ISSUE THREAD

**Issue by vjrantal** [Azure/azure-iot-connected-factory#48]
To reproduce, deploy the solution using [https://www.azureiotsolutions.com/Accelerators](https://www.azureiotsolutions.com/Accelerators) and check in Azure portal what ends up being set as the timestamp property name in Time Series Insights:

<img width="296" alt="Screenshot 2019-05-13 at 11 03 10" src="https://user-images.githubusercontent.com/207474/57605412-3efb7f80-756f-11e9-98fb-ef2facae5b43.png">

The expected value in above should be `Value.SourceTimestamp`.

The root cause is that this line https://github.com/Azure/azure-iot-connected-factory/blob/5eed3873c7e3d9ab84d33077d58bb17c3a629ce2/Deployment/Connectedfactory.json#L871 is missing brackets.

**Comment by barnstee** [comment]
Closed as this has been fixed.
