### ISSUE TITLE
Time Series Insight, OEE and KPI not works when deployed by build.ps1

### ISSUE THREAD

**Issue by ryan-ms** [Azure/azure-iot-connected-factory#50]
Hi

I just clone the latest repo(with OPC twin integrated), and use ./build.ps1 to provision the connected factory, and it sucessfully deployed.

After I deployed, I did not do anything, but I found that time series insight is not working, so chart of OEE, KPI is also not working. 

My Connected Factoty Picture
![issue1](https://user-images.githubusercontent.com/29178018/57921658-7308d480-78d0-11e9-874b-5e23c89e50ee.png)

Error log when open Time series insight line chart panel
![issue2](https://user-images.githubusercontent.com/29178018/57921888-093cfa80-78d1-11e9-8abc-211dcca4b257.JPG)

![issue3](https://user-images.githubusercontent.com/29178018/57921894-0b06be00-78d1-11e9-9d43-b26a593d7806.JPG)

Could you check the code? or did I do something wrong?
Looking forward for your reply, thank you.

**Comment by ryan-ms** [comment]
After using www.azureiotsolutions.com to deploying the solution, it's not happen again, I think it can close now.

**Comment by ni3git** [comment]
I am facing this issue too. Any pointers or resolution?
