### ISSUE TITLE
ASPNETCOMPILER : error ASPRUNTIME: '/temp' is not a valid IIS application. 

### ISSUE THREAD

**Issue by jjgriff93** [Azure/azure-iot-connected-factory#62]
When running the build.ps1 script, I get the following error:

ASPNETCOMPILER : error ASPRUNTIME: '/temp' is not a valid IIS application. [C:\Users\jamesgr\desktop\azure-iot-connecte
d-factory\WebApp\WebApp.csproj]

I've made no changes to the source code and followed the instructions closely, not sure what's wrong at a guess the web project within the VS solution doesn't seem to be able to locate the proper virtual directory.

**Comment by marcschier** [comment]
Can you provide us with the log output of the script?  Likely an issue with path separators.

**Comment by johnadali** [comment]
Hello,
   I am having the same issue as jjgriff93. I have followed the instructions exactly, except I am using Visual Studio 2019 Enterprise, so I had to modify the environment variables. I am attaching the log file that I received when running the build.ps1 script file, along with a screenshot of the environment variables in my Powershell session.

I have also made no changes to the source code, so I'm not sure why I am getting this error.

Please advise.

Thanks.
[connfactory.log](https://github.com/Azure/azure-iot-connected-factory/files/4418475/connfactory.log)
![connfactoryerror1](https://user-images.githubusercontent.com/20994182/78202799-e10fa900-745a-11ea-8444-036757d3cd0f.jpg)
![connfactory-envvariables](https://user-images.githubusercontent.com/20994182/78202803-e3720300-745a-11ea-9e81-99b1bf04841a.jpg)

**Comment by dacolgit** [comment]
Take a look here:
https://stackoverflow.com/questions/37779818/mvcbuildviews-true-causes-temp-is-not-a-valid-iis-application-error
https://developercommunity.visualstudio.com/content/problem/94528/when-setting-true-errror-aspruntime-temp-is-not-a.html
It's a Visual Studio issue.
