### ISSUE TITLE
BuildOutput bug

### ISSUE THREAD

**Issue by Almagnus1** [Azure/azure-iot-connected-factory#70]
If you create the directory "azure-iot-connected-factory\Simulation\Factory\buildOutput" before running build.ps1, the build script will succeed.

Otherwise, the build script will create a file named "buildOutput" in "azure-iot-connected-factory\Simulation\Factory" and you will see massive errors as a result of a file not being a directory.

**Comment by dacolgit** [comment]
Please update to the latest version.
The build script create both a BuildOutput.tar file in "azure-iot-connected-factory\Simulation\Factory" and a "BuildOutput" folder in
"azure-iot-connected-factory\Simulation\Factory\buildOutput"
