### ISSUE TITLE
OPC => IoT Hub Communication needs clarification

### ISSUE THREAD

**Issue by Almagnus1** [Azure/azure-iot-connected-factory#71]
I'm going through the documents, and having more documentation around how the OPC server is communicating with the IoT Hub would be helpful, especially since it looks like most of the OPC configurations are being generated dynamically.

More documentation around how the communication works would be helpful, as it's pretty opaque atm.

**Comment by dacolgit** [comment]
Azure IIoT gitHub:
https://github.com/Azure/Industrial-IoT

Azure IIoT docs:
https://azure.github.io/Industrial-IoT/
