### ISSUE TITLE
Remove-AzureRmADAppCredential - Parameter set cannot be resolved using the specified named parameters

### ISSUE THREAD

**Issue by bhushanpanhale** [Azure/azure-iot-connected-factory#73]
I am trying to deploy source code using

`./build.ps1 cloud -DeploymentName connectedfactoryv -Configuration release -LowCost`

But having below issue, All services deployed successfully but there are no alerts displayed on Dashboard. When I saw trace log it say Authentication failed.
![image](https://user-images.githubusercontent.com/58296656/69805753-59ddca80-1207-11ea-98ed-9079d2d966e7.png)

**Comment by dacolgit** [comment]
Which version of AzureRm have you installed?

**Comment by dacolgit** [comment]
Please update to latest Connected Factory version and check your AzureRm version. Supported version is 6.13.x
