### ISSUE TITLE
build script error: Add-AzureAccount 

### ISSUE THREAD

**Issue by jrd6dk** [Azure/azure-iot-connected-factory#74]
Hi,
It seems the service account I need to run the script needs to be administrator / owner of the subscription. Is this really true?
To me it seems a bit over reaching to require that level of rights.

Is there a document describing the access needed to deploy the connected factory.
I have a resource group on which the account has rights. 
The account is contributor to the subscription.

cheers
Jesper

----------------------------------------------------------------
VERBOSE: 2019-12-05 13:53:18Z - Add new Azure account
Add-AzureAccount : No subscriptions are associated with the logged in account in Azure Service Management (RDFE). This means that the logged in user is not an administrator or co-administrator for any account.\r\nDid you mean to execute Connect-AzureRmAccount?
At C:\Users\jeras\source\customers\azure-iot-connected-factory-2019-12-05\build.ps1:624 char:24
+ ...  $account = Add-AzureAccount -Environment $script:AzureEnvironment.Na ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Add-AzureAccount], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Profile.AddAzureAccount

**Comment by dacolgit** [comment]
The deployment script tries to register Azure Active Directory (AAD) applications. These requires admin rights.
