### ISSUE TITLE
Question: Connect opc server

### ISSUE THREAD

**Issue by PedroFloresGuillen** [Azure/azure-iot-connected-factory#9]
It is possible to connect an opc server to the webpage without connecting the gateway and proxy using docker, instead just using the normal console or visual studio?

**Comment by hansgschossmann** [comment]
To some extend this is possible, if you use the same telemetry format as the publisher is using. But certain functionality of the the CF solution like the OPC server browser command and control will not work.
If you do not like docker, you could also build and run the publisher/proxy from source code in github.

**Comment by PedroFloresGuillen** [comment]
Thanks.
